routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');
	

	//Route::post('users/{status}/approve', ['as' => 'status.approve', 'uses' => 'LoanersController@approve']); 
	Route::get('/users/{status}', ['as' => 'status.show', 'uses' => 'LoanersController@show']);
	

	Route::resource('/users', 'LoanersController');
	Route::resource('/product', 'ProductController');
	Route::resource('/cleared', 'ClearedController');
	Route::resource('/paid', 'PaidController');

	//Route::get('/customers','LoanersController@index')->name('customers.index');

	//Route::get('/','ApprovedController@index')->name('Notifications.index');

	Route::get('/approved','ApprovedController@index')->name('approved.index');
	

	Route::get('/declined','DeclinedController@index')->name('declined.index');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');

	Route::any('/search',function(){
		$q = Input::get ( 'q' );
		$user = User::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->orWhere('id_number','LIKE','%'.$q.'%')->orWhere('msisdn','LIKE','%'.$q.'%')->get();
		if(count($user) > 0)
			return view('users.search')->withDetails($user)->withQuery ( $q );
		else return view ('users.search')->withMessage('No Details found. Try to search again !');
	});

});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','role','phone_number', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    protected $table='adminusers';
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/users.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class users extends Model
{
    protected $table = 'users';
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the users
     *
     * @param  \App\User  $model
     * @return \Illuminate\View\View
     */
    public function index(User $model)
    {
        return view('users.index', ['users' => $model->paginate(15)]);
    }

    /**
     * Show the form for creating a new user
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a newly created user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $model
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(UserRequest $request, User $model)
    {
        $model->create($request->merge(['password' => Hash::make($request->get('password'))])->all());

        return redirect()->route('user.index')->withStatus(__('User successfully created.'));
    }

    /**
     * Show the form for editing the specified user
     *
     * @param  \App\User  $user
     * @return \Illuminate\View\View
     */
    public function edit(User $user)
    {
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified user in storage
     *
     * @param  \App\Http\Requests\UserRequest  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UserRequest $request, User  $user)
    {
        $user->update(
            $request->merge(['password' => Hash::make($request->get('password'))])
                ->except([$request->get('password') ? '' : 'password']
        ));

        return redirect()->route('user.index')->withStatus(__('User successfully updated.'));
    }

    /**
     * Remove the specified user from storage
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User  $user)
    {
        $user->delete();

        return redirect()->route('user.index')->withStatus(__('User successfully deleted.'));
    }
}

resources/views/users/add_products.blade.php
@extends('layouts.app', ['activePage' => 'products', 'titlePage' => __('Products')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <form method="post" action="{{ route('product.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Add Product') }}</h4>
                <p class="card-category"><i>Create a new product</i></p>
              </div>
              <div class="card-body ">
                <div class="row">
                  <div class="col-md-12 text-right">
                      <a href="{{ route('product.index') }}" class="btn btn-sm btn-primary">{{ __('Back to list') }}</a>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Product ID') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('product_id') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('product_id') ? ' is-invalid' : '' }}" name="product_id" id="input-product_id" type="number" placeholder="{{ __('Product ID') }}" value="{{ old('product_id') }}" required />
                      @if ($errors->has('product_id'))
                        <span id="product_id-error" class="error text-danger" for="input-product_id">{{ $errors->first('product_id') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Type') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('type') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type" id="input-type" type="text" placeholder="{{ __('Type') }}" value="{{ old('type') }}" required />
                      @if ($errors->has('type'))
                        <span id="type-error" class="error text-danger" for="input-type">{{ $errors->first('type') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Product Name') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('product_name') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('product_name') ? ' is-invalid' : '' }}" name="product_name" id="input-product_name" type="text" placeholder="{{ __('Product name') }}" value="{{ old('product_name') }}" required />
                      @if ($errors->has('product_name'))
                        <span id="product_name-error" class="error text-danger" for="input-product_name">{{ $errors->first('product_name') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Amount') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('amount') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('amount') ? ' is-invalid' : '' }}" name="amount" id="input-amount" type="number" placeholder="{{ __('Amount') }}" value="{{ old('amount') }}" required />
                      @if ($errors->has('amount'))
                        <span id="amount-error" class="error text-danger" for="input-amount">{{ $errors->first('amount') }}</span>
                      @endif
                    </div>
                  </div>
                </div>

                <div class="row">
                  <label class="col-sm-2 col-form-label" >{{ __(' Period') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('period') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('period') ? ' is-invalid' : '' }}" input type="period" name="period" id="input-period" placeholder="{{ __('Period') }}" value="" required />
                      @if ($errors->has('period'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('period') }}</span>
                      @endif
                    </div>
                  </div>
                </div>
                <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary text-center">{{ __('Add Product') }}</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/approved.blade.php
@extends('layouts.app', ['activePage' => 'approved', 'titlePage' => __('Pending Loans')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title " style="text-align:center">{{ __('Approved Loans') }}</h4>
                {{--<p class="card-category"> {{ __('Here you can manage users') }}</p>--}}
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                {{--<div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Add user') }}</a>
                  </div>
                </div>--}}
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-danger">
                      <th>
                        {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Phone') }}
                      </th>
                      <th>
                        {{ __('Product') }}
                      </th>
                      <th>
                        {{ __('Price') }}
                      </th>
                      
                      
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                        <tr>
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->msisdn }}
                          </td>
                          <td>
                            {{ $user->product_name }}
                          </td>
                          <td>
                            {{ $user->product_amount }}
                          </td>
                          
                          <td class="td-actions text-right">

                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/borrowers.blade.php
@extends('layouts.app', ['activePage' => 'borrowers', 'titlePage' => __('Pending Loans')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Pending Loans') }}</h4>
                <p class="card-category"> {{ __('Here you can manage requests') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                {{--<div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Add user') }}</a>
                  </div>
                </div>--}}
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-danger">
                      <th>
                        {{ __('ID') }}
                      </th>
                      <th>
                        {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Phone') }}
                      </th>
                      <th>
                        {{ __('Product') }}
                      </th>
                      <th>
                        {{ __('Price') }}
                      </th>
                      <th>
                        {{ __('Request Date') }}
                      </th>
                      
                      <th class="text-center">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                        <tr>
                          <td>
                            {{ $user->response_id }}
                          </td>
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->msisdn }}
                          </td>
                          <td>
                            {{ $user->product_name }}
                          </td>
                          <td>
                            {{ $user->product_amount }}
                          </td>
                          <td>
                            {{ $user->created_at }}
                          </td>
                          
                          
                          <td class="td-actions text-right">
                            
                             <form action="{{ route('users.update', $user->response_id) }}" method="post">
                                  @csrf
                                  {{ method_field('PUT')}}
                                  <input type="hidden" name="action" value="approve">
                                  <button type="submit" value="{{ $user->response_id }}" class="btn btn-success " data-original-title="" title="">
                                      Approve
                                  </button>
                                  
                             <div style="float:right; padding-left:3px;"></form>
                             <form action="{{ route('users.update', $user->response_id) }}" method="post">   
                                  @csrf
                                  {{ method_field('PUT')}}
                                  <input type="hidden" name="action" value="decline">
                                  <button type="submit" value="{{ $user->response_id }}" class="btn btn-danger " data-original-title="" title="">
                                      Decline
                                  </button>
                              </form></div>

                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  
@endsection

resources/views/users/cleared.blade.php
@extends('layouts.app', ['activePage' => 'borrowers', 'titlePage' => __('Pending Loans')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Clearance') }}</h4>
                <p class="card-category"> <i>{{ __('Clear clients') }}</i></p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                {{--<div class="row">
                  <div class="col-12 text-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Add user') }}</a>
                  </div>
                </div>--}}
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-danger">
                      <th>
                        {{ __('ID') }}
                      </th>
                      <th>
                        {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Phone') }}
                      </th>
                      <th>
                        {{ __('Product') }}
                      </th>
                      <th>
                        {{ __('Price') }}
                      </th>
                      
                      <th class="text-right">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                        <tr>
                          <td>
                            {{ $user->response_id }}
                          </td>
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->msisdn }}
                          </td>
                          <td>
                            {{ $user->product_name }}
                          </td>
                          <td>
                            {{ $user->product_amount }}
                          </td>
                          
                          
                          <td class="td-actions text-right">
                            
                             <form action="{{ route('cleared.update', $user->response_id) }}" method="post">
                                  @csrf
                                  {{ method_field('PUT')}}
                                  <input type="hidden" name="action" value="clear">
                                  
                                  <button type="submit" value="{{ $user->response_id }}" class="btn btn-success " data-original-title="" title="">                                     
                                  Clear
                                  </button>
                                </form>

                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
  
@endsection

resources/views/users/index.blade.php
@extends('layouts.app', ['activePage' => 'user-management', 'titlePage' => __('User Management')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Users') }}</h4>
                <p class="card-category"> {{ __('Here you can manage users') }}</p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row" style="padding-bottom:20px">
                  <div class="col-12 text-right">
                    <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary">{{ __('Add user') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-danger">
                      <th>
                          {{ __('Name') }}
                      </th>
                      <th>
                        {{ __('Email') }}
                      </th>
                      <th>
                        {{ __('Creation date') }}
                      </th>
                      <th class="text-right">
                        {{ __('Actions') }}
                      </th>
                    </thead>
                    <tbody>
                      @foreach($users as $user)
                        <tr>
                          <td>
                            {{ $user->name }}
                          </td>
                          <td>
                            {{ $user->email }}
                          </td>
                          <td>
                            {{ $user->created_at->format('Y-m-d') }}
                          </td>
                          <td class="td-actions text-right">
                            @if ($user->id != auth()->id())
                              <form action="{{ route('user.destroy', $user) }}" method="post">
                                  @csrf
                                  @method('delete')
                              
                                  <a rel="tooltip" class="btn btn-success " href="{{ route('user.edit', $user) }}" data-original-title="" title="">
                                    Edit
                                  </a>
                                  <button type="button" class="btn btn-danger " data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this user?") }}') ? this.parentElement.submit() : ''">
                                    Remove
                                  </button>
                              </form>
                            @else
                              <a rel="tooltip" class="btn btn-success " href="{{ route('profile.edit') }}" data-original-title="" title="">
                                Edit
                              </a>
                            @endif
                          </td>
                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/users/products.blade.php
@extends('layouts.app', ['activePage' => 'products', 'titlePage' => __('Product')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header card-header-primary">
                <h4 class="card-title ">{{ __('Products') }}</h4>
                <p class="card-category"><i> {{ __('Here are some of the products offered') }}</i></p>
              </div>
              <div class="card-body">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif
                <div class="row">
                  <div class="col-12 text-right" style="padding-bottom:20px">
                    <a href="{{ route('product.create') }}" class="btn btn-sm btn-primary">{{ __('Add Product') }}</a>
                  </div>
                </div>
                <div class="table-responsive">
                  <table class="table">
                    <thead class=" text-danger">
                      <th>
                        {{ __('Product ID') }}
                      </th>
                      <th>
                        {{ __('Type') }}
                      </th>
                      <th>
                        {{ __('Product Name') }}
                      </th>
                      <th>
                        {{ __('Price') }}
                      </th>
                      <th>
                        {{ __('Period') }}
                      </th>
                      <th class="text-right">
                        {{ __('Action') }}
                      </th>

                    </thead>
                    <tbody>
                      @foreach($product as $products)
                        <tr>
                          <td>
                            {{ $products->product_id }}
                          </td>
                          <td>
                            {{ $products->type }}
                          </td>
                          <td>
                            {{ $products->product_name }}
                          </td>
                          <td>
                            {{ $products->amount }}
                          </td>
                          <td>
                            {{ $products->period }}
                          </td>
                          <td class="td-actions text-right ">
                          <form method="post" id="delete-form" action="{{ route('product.destroy',$products->product_id)}}">
                            @csrf
                            @method('delete')
                        
                            <button type="button" class="btn btn-danger " data-original-title="" title="" onclick="confirm('{{ __("Are you sure you want to delete this product, it might be in use?") }}') ? this.parentElement.submit() : ''">
                              Remove
                            </button>
                          </form>
                          </td>


                        </tr>
                      @endforeach
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
@endsection