routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');
	

	//Route::post('users/{status}/approve', ['as' => 'status.approve', 'uses' => 'LoanersController@approve']); 
	Route::get('/users/{status}', ['as' => 'status.show', 'uses' => 'LoanersController@show']);
	

	Route::resource('/users', 'LoanersController');
	Route::resource('/product', 'ProductController');
	Route::resource('/cleared', 'ClearedController');
	Route::resource('/paid', 'PaidController');

	//Route::get('/customers','LoanersController@index')->name('customers.index');

	//Route::get('/','ApprovedController@index')->name('Notifications.index');

	Route::get('/approved','ApprovedController@index')->name('approved.index');
	

	Route::get('/declined','DeclinedController@index')->name('declined.index');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');

	Route::any('/search',function(){
		$q = Input::get ( 'q' );
		$user = User::where('name','LIKE','%'.$q.'%')->orWhere('email','LIKE','%'.$q.'%')->orWhere('id_number','LIKE','%'.$q.'%')->orWhere('msisdn','LIKE','%'.$q.'%')->get();
		if(count($user) > 0)
			return view('users.search')->withDetails($user)->withQuery ( $q );
		else return view ('users.search')->withMessage('No Details found. Try to search again !');
	});

});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar" data-color="orange" data-background-color="white" data-image="{{ asset('material') }}/img/sidebar-1.jpg">
  <!--
      Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

      Tip 2: you can also add an image using data-image tag
  -->
  <div class="logo">
    <a href="{{ route('home') }}" class="simple-text logo-normal">
      <img src="/material/img/powerpay.png" alt="powerpay" height="40" width="150">
    </a>
  </div>
  <div class="sidebar-wrapper">
    <ul class="nav">
      <li class="nav-item{{ $activePage == 'dashboard' ? ' active' : '' }}">
        <a class="nav-link" href="{{ route('home') }}">
          <i class="material-icons">dashboard</i>
            <p>{{ __('Dashboard') }}</p>
        </a>
      </li>
      <li class="nav-item {{ ($activePage == 'profile' || $activePage == 'user-management') ? ' active' : '' }}">
        <a class="nav-link" data-toggle="collapse" href="#laravelExample" aria-expanded="true">
          <i class="material-icons">library_books</i>
          <p>{{ __('Profiles') }}
            <b class="caret"></b>
          </p>
        </a>
        <div class="collapse show" id="laravelExample">
          <ul class="nav">
            <li class="nav-item{{ $activePage == 'profile' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('profile.edit') }}">
                <span class="sidebar-mini"> <strong>UP </strong> </span>
                <span class="sidebar-normal">{{ __('User profile') }} </span>
              </a>
            </li>
            <li class="nav-item{{ $activePage == 'user-management' ? ' active' : '' }}">
              <a class="nav-link" href="{{ route('user.index') }}">
                <span class="sidebar-mini"><strong> UM </strong></span>
                <span class="sidebar-normal "> {{ __('User Management') }} </span>
              </a>
            </li>
          </ul>
        </div>
      </li>
      <li class="nav-item{{ $activePage == 'users.index' ? 'active' : ''}}">
        <a class="nav-link "href="{{route('product.index')}}" >
          <i class="material-icons">local_mall</i>
          <p>{{__('Products')}}</p>
        </a>
       
    </li>

      <li class="nav-item{{ $activePage == 'users.index' ? 'active' : ''}}">
        <a class="nav-link "href="{{route('users.index')}}" >
          <i class="material-icons">content_paste</i>
          <p>{{__('Pending Loans')}}</p>
        </a>
       
    </li>
    <li class="nav-item{{ $activePage == 'cleared.index' ? 'active' : ''}}">
      <a class="nav-link "href="{{route('cleared.index')}}" >
        <i class="material-icons">content_paste</i>
        <p>{{__('Clearance')}}</p>
      </a>
    </li>
    <li class="nav-item{{ $activePage == 'table' ? ' active' : '' }}">
      <a class="nav-link" href="{{route('paid.index')}}">
        <i class="material-icons">verified_user</i>
          <p>{{ __('Cleared Loans') }}</p>
      </a>
    </li>
     
  </li>
      <li class="nav-item{{ $activePage == 'table' ? ' active' : '' }}">
        <a class="nav-link" href="{{route('approved.index')}}">
          <i class="material-icons">assignment_turned_in</i>
            <p>{{ __('Approved Loans') }}</p>
        </a>
      </li>
      <li class="nav-item{{ $activePage == 'table' ? ' active' : '' }}">
        <a class="nav-link" href="{{route('declined.index')}}">
          <i class="material-icons">assignment_late</i>
            <p>{{ __('Declined Loans') }}</p>
        </a>
      </li>
    
      
       
      


    </ul>
  </div>
</div>